### ISSUE TITLE
Confused by resolveVersion

### ISSUE THREAD

**Issue by jimisaacs** [esm-dev/esm.sh#168]
@ije I'm really not understanding what `resolveVersion` does. It literally looks like it is removing semver constraint symbols from a version constraint, and calling that "resolved".

Example:
https://github.com/alephjs/esm.sh/blob/c8be4051019116a99a741545185985c0866226c0/server/nodejs.go#L335-L337

How is that logic right? If the package constraint is `react@<17`, how does that come to mean `react@latest` (which is 17). The rest of the function is also confusing, as it's just removing symbols rather than actually resolving from what I am attempting to understand.

If you have some time, can you please explain this function?

**Comment by ije** [comment]
no the logic from 335 to 337  is not right acctually! it should be fixed. the rest is to simplify the version exresssion, because when we fetch package info form npm we can get all the versions of the package, then we must decide to which version we should use. 
check: https://github.com/alephjs/esm.sh/blob/c8be4051019116a99a741545185985c0866226c0/server/nodejs.go#L292

**Comment by jimisaacs** [comment]
thanks, I'll look more there

**Comment by jimisaacs** [comment]
@ije would you be apposed to using something like or maybe even exactly this? https://github.com/Masterminds/semver

**Comment by ije** [comment]
oh

**Comment by ije** [comment]
this https://github.com/Masterminds/semver looks great

**Comment by ije** [comment]
would you create a pr on it? currently i am focusing on the new cjs lexer in rust instead of the cjs-module-lexer and evel for some safety reasons

**Comment by ije** [comment]
switch to https://github.com/Masterminds/semver in v65
