### ISSUE TITLE
Pinning does not propagate in .d.ts files

### ISSUE THREAD

**Issue by zaboco** [esm-dev/esm.sh#339]
## Issue
Pinning a TS type definition file does not propagate to the imported files.

## Reproduction
1. Request `react` pinned to an older esm.sh version (e.g. `v65`) - https://esm.sh/react@18.1.0?pin=v65
2. Get the .d.ts URL from the `x-typescript-types` header - https://esm.sh/v65/@types/react@^18/index.d.ts. This step works fine, the root `d.ts` is pinned to `v65`
3. Download [the `.d.ts` file](https://esm.sh/v65/@types/react@^18/index.d.ts)

### Expected
The imports are pinned to version `v65`. E.g.:
```js
import * as CSS from 'https://esm.sh/v65/csstype@3.1.0/index.d.ts';
```

### Actual
The imports are pinned to the latest version (`v85` at this time):
```js
import * as CSS from 'https://esm.sh/v85/csstype@3.1.0/index.d.ts';
```

**Comment by tv42** [comment]
A second, I think related, issue is that the types package version shifts over time. I just had a build fail because my lock file had

`https://esm.sh/v86/@types/react@18.0.14/global.d.ts` etc

where what seems to be needed now is

`https://esm.sh/v86/@types/react@18.0.15/global.d.ts`.

The header returned is

```
$ curl -s -i 'https://esm.sh/react@18.1.0/jsx-runtime?pin=v86' | grep '^x-typescript-types:'
x-typescript-types: https://esm.sh/v86/@types/react@^18/jsx-runtime~.d.ts
````

Where you can see it's `^18` not a specific version.

This causes breakage of any lockfile-using builds every time any `@types/*` package sees a patch release.

**Comment by ije** [comment]
the server returns a fixed `@types/react` now
