### ISSUE TITLE
Failed to import - `@supabase/auth-helpers-shared@0.3.0` dependency

### ISSUE THREAD

**Issue by iuioiua** [esm-dev/esm.sh#572]
## Failing module

- **GitHub**: https://github.com/supabase/auth-helpers
- **npm**: https://www.npmjs.com/package/@supabase/auth-helpers-shared

```js
import { something } from "https://esm.sh/@supabase/auth-helpers-shared@0.3.0"
```

## Error message

After running `deno info https://esm.sh/@supabase/auth-helpers-shared@0.3.0`, the file `https://esm.sh/v113/@supabase/supabase-js@2.12.1/dist/module/lib/types/dist/module/index.d.ts` was reported as missing. It's pointed to by `https://esm.sh/v113/@supabase/auth-helpers-shared@0.3.0/dist/index.d.ts` for some reason.

This missing file slows down startup times as the startup pauses until concluding that this file is missing. As a workaround, I've had to `deno run --cached-only...`

Is this a fault of the package or ESM?

## Additional info

- **esm.sh version**: v113
- **Deno version**: v1.32.1

## Related:
* supabase/auth-helpers#471

**Comment by ije** [comment]
thanks, i will look into it.

**Comment by iuioiua** [comment]
Thank you 🙏🏾
FYI, this is for https://github.com/denoland/saaskit

**Comment by marvinhagemeister** [comment]
I took a look into this and can confirm that this is an error in the resolution logic of `esm.sh`. Currently, we only consider paths in `package.json` to be a valid resolution targets. This works pretty well for the majority of cases, but is different from how TypeScript resolves types.

The `https://esm.sh/v113/@supabase/auth-helpers-shared@0.3.0/dist/index.d.ts` file has a relative import to `@supabase/supabase-js/dist/module/lib/types`:

```ts
import * as _supabase_supabase_js_dist_module_lib_types from '@supabase/supabase-js/dist/module/lib/types';
```

But because there is no `.exports` entry in `package.json` in `@supabase/supabase-js` it just falls back to the value defined in `.types` and appends that to the current path. That's wrong because that is intended for the main entry. Instead what should have happened is that `esm.sh` checks first if there is a `@supabase/supabase-js/dist/module/lib/types.d.ts` file. That will return the correct typing file.

Problem is that the current architecture doesn't store these in `esm.sh`'s internal cache.

**Comment by iuioiua** [comment]
Thank you! When can we expect a new release for these fixes?

**Comment by ije** [comment]
> Thank you! When can we expect a new release for these fixes?

working on it

**Comment by ije** [comment]
done! @iuioiua can you please confirm? thanks

**Comment by iuioiua** [comment]
Issue fixed! Thank you very much 🙏🏾
