### ISSUE TITLE
Failed to import - openai@4.12.4

### ISSUE THREAD

**Issue by higebu** [esm-dev/esm.sh#743]
## Failing module

- **GitHub**: https://github.com/openai/openai-node
- **npm**: https://www.npmjs.com/package/openai

```js
import OpenAI from "https://esm.sh/openai@4.12.4"
```

## Error message

After running `deno run` I got this:

```
error: Module not found "https://esm.sh/v133/openai@4.12.4/denonext/resources.js".
    at https://esm.sh/openai@4.12.4:2:8
```

## Additional info

- **esm.sh version**: v133
- **Deno version**: 1.37.2
- Example of main.ts

```typescript
import OpenAI from "https://esm.sh/openai@4.12.4";

if (import.meta.main) {
    const openai = new OpenAI();
    const completion = await openai.chat.completions.create({
        messages: [{ role: 'user', content: 'Say this is a test' }],
        model: 'gpt-3.5-turbo',
    });
    console.log(completion.choices);
}
```

**Comment by jedwards1211** [comment]
Does esm.sh support package name self-reference in import/require statements?  `openai` uses package name self-reference and an export map with wildcards, so my hunch is there's some issue with how esm.sh handles that.

**Comment by rattrayalex** [comment]
I am a maintainer of the `openai` npm package; this bug is also being discussed here: https://github.com/openai/openai-node/issues/393.

Note that 
```ts
import OpenAI from "https://esm.sh/openai@4.11.0"
```
does work, but all more recent versions, including 4.12.0, do not work. The diff from 4.11.0 to 4.12.0 is here: https://github.com/openai/openai-node/compare/v4.11.1...v4.12.0

Though note some of those changes (such as `export type` -> `export import`) were later reverted.

There is no `resources.js` in our codebase, only a `resources` folder with an `index.js`. None of our imports attempt to import from eg  `'./resources'` without doing `'./resources/index.js'` or equivalent, so I suspect this may be a bug in esm.sh's module resolution magic.

**Comment by rattrayalex** [comment]
cc @ije since I think this may be a regression…

**Comment by ije** [comment]
just deploy a fix patch for the issue, it should work again(also a testing added)

**Comment by ije** [comment]
sorry for the late update

**Comment by rattrayalex** [comment]
Thank you so much @ije !
