### ISSUE TITLE
Failed to import - `many-keys-map` | Old Pluto.jl exports

### ISSUE THREAD

**Issue by pankgeorg** [esm-dev/esm.sh#879]
## Failing module

- **GitHub**: https://github.com/fonsp/Pluto.jl - https://github.com/fregante/many-keys-map
- **npm**: https://www.npmjs.com/package/many-keys-map

```js
import ManyKeysWeakMap from "https://cdn.esm.sh/v64/many-keys-weakmap@1.0.0/es2021/many-keys-weakmap.js"

```

## Error message

After `onload` I got this:

```
GET https://esm.sh/v64/many-keys-weakmap@1.0.0/es2021/many-keys-weakmap.js net::ERR_ABORTED 500 (Internal Server Error)

```

## Additional info

- **esm.sh version**: 64
- **Browser version**: Latest Chrome

crossref: https://github.com/fonsp/Pluto.jl/issues/3019 and https://github.com/fonsp/Pluto.jl/issues/2707
context:
Pluto HTML bundles that are on the internet and refer to ESM are more-or-less immutable, as they were usually built as part of some course that has now ended, so it's not maintained.

**Comment by ije** [comment]
the url should be [https://esm.sh/v64/many-keys-weakmap@1.0.0/es2021/many-keys-weakmap.mjs](https://esm.sh/v64/many-keys-weakmap@1.0.0/es2021/many-keys-weakmap.mjs) now

**Comment by fonsp** [comment]
Hey! The problem in our project is that we version-pinned the esm.sh URL to future-proof the import. So we used 

```js
import ManyKeysWeakMap from "https://cdn.esm.sh/v64/many-keys-weakmap@1.0.0/es2021/many-keys-weakmap.js"
```

with the assumption that this would work forever, by pinning the esm.sh version, the package version and the compile target.

This import is baked into some archived html files that we generated in the past, and these files suddenly stopped working. Since this was an archival project, we can't change the import.

Is it possible to make the original import (with `.js`) work again, for versions where this worked in the past?

**Comment by fonsp** [comment]
Hi @ije, could you take a look at this?

**Comment by ije** [comment]
@pankgeorg i will fix it asap！

**Comment by ije** [comment]
hi @fonsp, i just added a patch for the issue, now it works again https://esm.sh/v64/many-keys-weakmap@1.0.0/es2021/many-keys-weakmap.js
